### ISSUE TITLE
Confusing failure when cloning inside an existing git project

### ISSUE THREAD

**Issue by tclune** [GEOS-ESM/mepo#224]
@wmputman attempted a `mepo clone` within a directory that already had a `.git`.    The failure message was at best confusing and may mean that mepo did not correctly detect the topdir at some point:
```
GIT/GEOS-v10p22p0> mepo clone -b v10.22.0 git@github.com:GEOS-ESM/GEOSgcm.git
env                    | (t) v3.13.0
cmake                  | (t) v3.12.0
ecbuild                | (t) geos/v1.2.0
fatal: cannot change to '/gpfsm/dnb03/projects/p38/GIT/GEOS-v10p22p0/./src/Shared/@NCEP_Shared': No such file or directory

Traceback (most recent call last):
  File "/discover/swdev/gmao_SIteam/mepo/mepo", line 17, in <module>
    main()
  File "/gpfsm/dswdev/gmao_SIteam/mepo/mepo.d/main.py", line 6, in main
    command.run(args)
  File "/gpfsm/dswdev/gmao_SIteam/mepo/mepo.d/command/command.py", line 11, in run
    cmd_module.run(args)
  File "/gpfsm/dswdev/gmao_SIteam/mepo/mepo.d/command/clone/clone.py", line 76, in run
    git.sparsify(comp.sparse)
  File "/gpfsm/dswdev/gmao_SIteam/mepo/mepo.d/repository/git.py", line 71, in sparsify
    shellcmd.run(shlex.split(cmd1))
  File "/gpfsm/dswdev/gmao_SIteam/mepo/mepo.d/utilities/shellcmd.py", line 15, in run
    result.check_returncode()
  File "/usr/local/other/python/GEOSpyD/4.10.3_py3.9/2022-01-14/lib/python3.9/subprocess.py", line 460, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command '['git', '-C', '/gpfsm/dnb03/projects/p38/GIT/GEOS-v10p22p0/./src/Shared/@NCEP_Shared', 'config', 'core.sparseCheckout', 'true']' returned non-zero exit status 128.
```

Clone was from within:  gpfsm/dnb03/projects/p38/GIT/GEOS-v10p22p0
which looked like this:
```
  /gpfsm/dnb03/projects/p38/GIT/GEOS-v10p22p0:
  total used in directory 101 available 218083531776
  drwxr-sr-x 10 wputman s1062 8192 Apr 12 11:37 GEOSgcm
  drwxr-sr-x  8 wputman s1062 8192 Apr 12 11:37 .
  drwxr-sr-x  8 wputman s1062 8192 Apr 11 22:10 .git
  drwxr-sr-x  2 wputman s1062  512 Apr 11 12:40 .mepo
  -rw-r--r--  1 wputman s1062  103 Apr 11 12:40 .gitignore
  drwxr-sr-x  4 wputman s1062  512 Apr 11 12:40 .github
  -rw-r--r--  1 wputman s1062  674 Apr 11 12:40 .editorconfig
  drwxr-sr-x  2 wputman s1062  512 Apr 11 12:40 .codebuild
  drwxr-sr-x  2 wputman s1062  512 Apr 11 12:40 .circleci
  drwxr-sr-x 38 wputman s1062 8192 Apr  9 20:34 ..
```

**Comment by mathomp4** [comment]
This is actually weirder than you think. I found a more perverse `mepo` issue looking at this. Give me a bit...
